# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('stake', models.FloatField()),
                ('contacts', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
    ]
