# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaking', '0002_horse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
